- name: Betterbird - Linux build
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    betterbird_patches:
      repository: https://github.com/Betterbird/thunderbird-patches.git
      directory: "{{ playbook_dir }}/betterbird-patches"

  tasks:
    - name: check for 64-bit linux
      shell:
        cmd: "uname -m"
      register: check_64bit
      changed_when: false
      failed_when: check_64bit.stdout != "x86_64"

    - name: install packages
      become: yes
      package:
        state: present
        name:
          - mercurial
          - python3
          - python3-pip

    - name: clone repos
      include_tasks: tasks/clone_repos.yml

    - name: prepare hg directories
      include_tasks: tasks/prepare_hg_dir.yml
      loop:
        - "{{ playbook_dir }}/source/.hg"
        - "{{ playbook_dir }}/source/comm/.hg"

    - name: purge repos
      shell:
        chdir: "{{ item }}"
        cmd: hg purge
      loop:
        - "{{ playbook_dir }}/source"
        - "{{ playbook_dir }}/source/comm"

    - name: apply patches
      include_tasks: tasks/apply_patches.yml

    - name: bootstrap
      shell:
        chdir: "{{ playbook_dir }}/source"
        cmd: >
          ./mach
          --no-interactive
          bootstrap
          --application-choice "Firefox for Desktop"

    - name: mozconfig setup
      lineinfile:
        path: "{{ playbook_dir }}/source/mozconfig"
        create: yes
        line: "{{ item }}"
      loop:
        - "ac_add_options --enable-application=comm/mail"
        - "ac_add_options --enable-official-branding"
        #
        - "ac_add_options --with-branding=comm/mail/branding/betterbird"
        #
        - "ac_add_options --disable-updater"
        - "ac_add_options --disable-crashreporter"
        #
        - "MOZ_REQUIRE_SIGNING="
        - "MOZ_REQUIRE_ADDON_SIGNING=0"
        #
        - "export MOZILLA_OFFICIAL=1"
        - "export MOZ_TELEMETRY_REPORTING="

    - name: build
      shell:
        chdir: "{{ playbook_dir }}/source"
        cmd: ./mach build

    - name: package
      shell:
        chdir: "{{ playbook_dir }}/source"
        cmd: ./mach package
