- name: apply patches | betterbird - find all patch files
  find:
    paths: "{{ betterbird_patches.directory }}/{{ current_release.directory }}"
    patterns: "*.patch"
    recurse: yes
  changed_when: false
  register: betterbird_patch_files

# ----------------------------------------------------------------------------------------------------------------------

- name: apply patches | mozilla - copy series file
  copy:
    src: "{{ betterbird_patches.directory }}/{{ current_release.directory }}/series-M-C"
    dest: "{{ playbook_dir }}/source/.hg/patches/series"

- name: apply patches | mozilla - copy betterbird patch files
  copy:
    src: "{{ item.path }}"
    dest: "{{ playbook_dir }}/source/.hg/patches/{{ item.path | basename }}"
  when: "'-m-c.patch' in item.path"
  loop: "{{ betterbird_patch_files.files }}"

- name: apply patches | mozilla - download additional patch files
  get_url:
    url: "{{ item | regex_search('http.*') | replace('/rev/','/raw-rev/') }}"
    dest: "{{ playbook_dir }}/source/.hg/patches/{{ item | regex_search('.*#') | replace('#','') | trim }}"
  when: "'http' in item"
  loop: "{{ lookup('file', playbook_dir + '/source/.hg/patches/series').split('\n') }}"

- name: apply patches | mozilla - apply all patch files
  shell:
    chdir: "{{ playbook_dir }}/source/.hg/patches"
    cmd: hg qpush -a

# ----------------------------------------------------------------------------------------------------------------------

- name: apply patches | comm - copy series file
  copy:
    src: "{{ betterbird_patches.directory }}/{{ current_release.directory }}/series"
    dest: "{{ playbook_dir }}/source/comm/.hg/patches/series"

- name: apply patches | comm - copy betterbird patch files
  copy:
    src: "{{ item.path }}"
    dest: "{{ playbook_dir }}/source/comm/.hg/patches/{{ item.path | basename }}"
  when: "not ('-m-c.patch' in item.path)"
  loop: "{{ betterbird_patch_files.files }}"

- name: apply patches | comm - download additional patches
  get_url:
    url: "{{ item | regex_search('http.*') | replace('/rev/','/raw-rev/') }}"
    dest: "{{ playbook_dir }}/source/comm/.hg/patches/{{ item | regex_search('.*#') | replace('#','') | trim }}"
  when: "'http' in item"
  loop: "{{ lookup('file', playbook_dir + '/source/comm/.hg/patches/series').split('\n') }}"

- name: apply patches | comm - apply all patch files
  shell:
    chdir: "{{ playbook_dir }}/source/comm/.hg/patches"
    cmd: hg qpush -a
