- name: apply patches | copy series file
  copy:
    src: "{{ item.series_file }}"
    dest: "{{ item.patches_directory }}/series"

- name: apply patches | copy betterbird patch files
  copy:
    src: "{{ betterbird_patch_file.path }}"
    dest: "{{ item.patches_directory }}/{{ betterbird_patch_file.path | basename }}"
  when: "{{ item.patch_file_filter }} in betterbird_patch_file.path"
  loop: "{{ betterbird_patch_files.files }}"
  loop_control:
    loop_var: betterbird_patch_file

- name: apply patches | download additional patch files
  get_url:
    url: "{{ series_file_item | regex_search('http.*') | replace('/rev/','/raw-rev/') }}"
    dest: "{{ item.patches_directory }}/{{ series_file_item | regex_search('.*#') | replace('#','') | trim }}"
  when: "'http' in series_file_item"
  loop: "{{ lookup('file', item.patches_directory + '/series').split('\n') }}"
  loop_control:
    loop_var: series_file_item

- name: apply patches | apply all patch files
  shell:
    chdir: "{{ item.patches_directory }}"
    cmd: hg qpush -a
