- name: clone mozilla
  community.general.hg:
    repo: "{{ repo.mozilla }}"
    dest: "{{ playbook_dir }}/source"
    force: yes
    purge: yes

- name: clone comm
  community.general.hg:
    repo: "{{ repo.comm }}"
    dest: "{{ playbook_dir }}/source/comm"
    force: yes
    purge: yes

- name: clone betterbird
  git:
    repo: "{{ repo.betterbird }}"
    dest: "{{ betterbird_patches.root_dir }}"
    depth: 1
