- name: clone repos | betterbird - clone
  git:
    repo: "{{ betterbird_patches.repository }}"
    dest: "{{ betterbird_patches.directory }}"
    force: yes
    depth: 1

- name: clone repos | betterbird - include releases.yml
  include_vars:
    file: "{{ betterbird_patches.directory }}/releases.yml"

# ----------------------------------------------------------------------------------------------------------------------

- name: clone repos | mozilla - check directory
  stat:
    path: "{{ playbook_dir }}/source"
  changed_when: false
  register: mozilla_directory

- name: clone repos | mozilla - clone
  shell:
    chdir: "{{ playbook_dir }}"
    cmd: "hg clone {{ current_release.repos.mozilla.url }} source/"
  when: not mozilla_directory.stat.exists

- name: clone repos | mozilla - pull
  shell:
    chdir: "{{ playbook_dir }}/source"
    cmd: "hg pull"
  when: mozilla_directory.stat.exists

- name: clone repos | mozilla - set revision
  shell:
    chdir: "{{ playbook_dir }}/source"
    cmd: "hg update -C -r {{ current_release.repos.mozilla.revision }}"

# ----------------------------------------------------------------------------------------------------------------------

- name: clone repos | comm - check directory
  stat:
    path: "{{ playbook_dir }}/source/comm"
  changed_when: false
  register: comm_directory

- name: clone repos | comm - clone
  shell:
    chdir: "{{ playbook_dir }}/source"
    cmd: "hg clone {{ current_release.repos.comm.url }} comm/"
  when: not comm_directory.stat.exists

- name: clone repos | comm - pull
  shell:
    chdir: "{{ playbook_dir }}/source/comm"
    cmd: "hg pull"
  when: comm_directory.stat.exists

- name: clone repos | comm - set revision
  shell:
    chdir: "{{ playbook_dir }}/source/comm"
    cmd: "hg update -C -r {{ current_release.repos.comm.revision }}"
