- name: mozconfig setup
  lineinfile:
    path: "{{ playbook_dir }}/source/mozconfig"
    create: yes
    line: "{{ item }}"
  loop:
    - "ac_add_options --enable-application=comm/mail"
    - "ac_add_options --enable-official-branding"
    #
    - "ac_add_options --with-branding=comm/mail/branding/betterbird"
    #
    - "ac_add_options --disable-updater"
    - "ac_add_options --disable-crashreporter"
    #
    - "MOZ_REQUIRE_SIGNING="
    - "MOZ_REQUIRE_ADDON_SIGNING=0"
    #
    - "export MOZILLA_OFFICIAL=1"
    - "export MOZ_TELEMETRY_REPORTING="
