- name: prepare hg dir | initialize patches directory
  block:
    - name: prepare hg dir | delete patches directory
      file:
        path: "{{ item }}/patches"
        state: absent
    - name: prepare hg dir | create patches directory
      file:
        path: "{{ item }}/patches"
        state: directory

- name: prepare hg dir | create "[extensions]" section in hgrc
  lineinfile:
    path: "{{ item }}/hgrc"
    create: yes
    regexp: "^\\[extensions\\]"
    insertafter: EOF
    line: "[extensions]"

- name: prepare hg dir | enable extensions
  lineinfile:
    path: "{{ item }}/hgrc"
    regexp: "^{{ extension }} ="
    insertafter: "\\[extensions\\]"
    line: "{{ extension }} ="
  loop:
    - mq
    - purge
  loop_control:
    loop_var: extension
