- name: create patch directory
  file:
    path: "{{ item }}/patches"
    state: directory

- name: create "[extensions]" section in hgrc
  lineinfile:
    path: "{{ item }}/hgrc"
    create: yes
    regexp: "^\\[extensions\\]"
    insertafter: EOF
    line: "[extensions]"

- name: enable "mq" extension
  lineinfile:
    path: "{{ item }}/hgrc"
    regexp: "^mq ="
    insertafter: "\\[extensions\\]"
    line: "mq ="
