- name: prepare hg dir | create patches directory
  file:
    path: "{{ hg_dir }}/patches"
    state: directory

- name: prepare hg dir | clear patch status file
  shell:
    chdir: "{{ hg_dir }}/patches"
    cmd: ": > status"

- name: prepare hg dir | create "[extensions]" section in hgrc
  lineinfile:
    path: "{{ hg_dir }}/hgrc"
    create: yes
    regexp: "^\\[extensions\\]"
    insertafter: EOF
    line: "[extensions]"

- name: prepare hg dir | enable extensions
  lineinfile:
    path: "{{ hg_dir }}/hgrc"
    regexp: "^{{ extension }} ="
    insertafter: "\\[extensions\\]"
    line: "{{ extension }} ="
  loop:
    - mq
    - purge
  loop_control:
    loop_var: extension
